# Generated by Django 2.2.1 on 2019-05-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.ImageField(upload_to='', verbose_name='画像ファイル'),
        ),
    ]
